coverage:
  status:
    project:
      default:
        threshold: 1%  # Allow coverage to drop by 1% and still pass
range: "70...100"  # Coverage color will range from 70% to 100%
comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"  # Layout of the coverage report
